H5_PLUGIN_PATH="${PREFIX}/lib/hdf5/plugin"

cmake -Bbuild -H. -G "Ninja" -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_FIND_ROOT_PATH=$PREFIX -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_INSTALL_PREFIX=${PREFIX} -DPLUGIN_INSTALL_PATH=${H5_PLUGIN_PATH}
cmake --build build --target install
