{% set name = "zstd-hdf5-plugin" %}
{% set version = "1.0.0" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
  - git_url: https://github.com/aparamon/HDF5Plugin-Zstandard
    git_depth: 1
  - path: cmake
    folder: .

build:
  number: 0
  skip: True  # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - hdf5
    - zstd
    - cmake
    - ninja
  run:
    - zstd
    - hdf5

test:
  files:
    - test_plugin.py
  requires:
    - h5py
    - python
  commands:
    - python test_plugin.py

about:
    license: 'BSD-3-Clause'
    license_file: 'LICENSE'
    home: https://github.com/aparamon/HDF5Plugin-Zstandard
    summary: HDF5 plugin for Zstandard filter
    description: |
        The plugin is being placed into HDF5 plugin directory, so it can be dynamically
        loaded. This enables the usage for other libraries like h5py. We use our own
        CMakeLists here to enable easy linking against Conda-Forges Zstandard library.

extra:
  recipe-maintainers:
    - sdebionne
